# Site
repository: ha36d/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hamed Faramarzi
title: Lead SRE
email: hamed@faramarzi.net
website: https://faramarzi.net

# Dark Mode
darkmode: true

# Social links
twitter_username: hammeeeddddd
github_username: ha36d
stackoverflow_username: "2358483"
# dribbble_username: jekyll
# facebook_username: jekyll
flickr_username: 200614930@N07
instagram_username: frame_hazard
linkedin_username: hamedfaramarzi
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: ha36d
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Medium
  icon: fab fa-medium
  url: https://medium.com/@hamed.faramarzi
- title: blog
  icon: fab fa-blogger
  url: https://blog.faramarzi.net
- title: wikipedia
  icon: fab fa-wikipedia-w
  url: https://fa.wikipedia.org/wiki/%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1:Ha36d
- title: Google Scholar
  icon: fab fa-google
  url: https://scholar.google.com/citations?user=uw1_e4wAAAAJ&hl=fr
- title: ResearchGate
  icon: fab fa-researchgate
  url: https://www.researchgate.net/profile/Hamed-Faramarzi

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"
# google_analytics_4: "G-H72SW6XP6V"
# gtag: "G-H72SW6XP6V"
# cmp: cookie-script
# cookie-scriptID: ecdc1fffedca95c3cc9bef0dc6ac8305

# About Section
# about_title: About Me
about_profile_image: images/newprofile.jpg
about_content: |
  Hi, I'm <b>Hamed</b> ‚Äî a passionate <b>Lead SRE</b> and tech junkie.
  When I'm not solving complex system challenges, you‚Äôll find me talking for hours about <mark>music</mark>, <mark>cinema</mark>, and <mark>craft beers</mark>.
  Whether it‚Äôs <b>development, DevOps, system engineering, networks, or voice solutions</b> ‚Äî count me in! üöÄ

  In my free time, I'm a <b>solo traveler</b> and an avid <b>photographer</b>.
  I‚Äôm also a <b>Berlin Marathon</b> finisher ‚Äî 1x marathon, 1x <a href="https://en.wikipedia.org/wiki/Iliotibial_band">IT band injury</a>.
  Currently, I'm putting my soul into creating my very first music album. üé∂ Check out my project <a href="https://mooziq.app/">MooziQ</a> ‚Äî still early days, but growing!

  Bonus skills?
  I'm pretty handy in the kitchen and behind the bar ‚Äî <mark>Cooking</mark> & <mark>Cocktail Making</mark> are my secret arts. üç≥üç∏

  <br>

    <div style="display:flex;align-items:center;gap:20px;margin-top:10px;margin-bottom:10px;">
      <a href="https://ketab.ir/book/4ae5fa2f-310b-413c-9239-2cf9b19e94f9" target="_blank" rel="noopener noreferrer">
        <img src="images/biganeh.jpg" alt="Biganeh Book Cover" style="width:180px;height:180px;border-radius:50%;object-fit:cover;">
      </a>
      <div style="font-size:1.4em;">
        My latest translation book (in Persian) is out. üìö Translating this book was a true labor of love.
      </div>
    </div>

content:
  - title: Experiences
    layout: list
    content:
      - layout: left
        title: Altair
        sub_title: Lead DevOps
        caption: April 2022 ‚Äì Present
        description: |
          Leading global cloud infrastructure initiatives.
      - layout: left
        title: Manomano
        sub_title: Staff SRE
        caption: May 2021 ‚Äì April 2022
        description: |
          Designed, implemented, and maintained infrastructure and SaaS services.
      - layout: left
        title: Diabolocom
        sub_title: Lead DevOps and Telecom
        caption: August 2017 ‚Äì May 2021
        description: |
          Led operations across 5 European datacenters and public clouds (AWS, GCP) and SaaS services.
          Tech Stack: Terraform, Ansible, K8s, Gitlab, Proxmox, Ceph, MySQL, PostgreSQL, ES, MongoDB, HA/LB for HTTP/RTC/SIP/RTP, BGP, IS-IS, Python.
      - layout: left
        title: Tosan
        sub_title: Senior System and Network Engineer
        caption: 2016 ‚Äì 2017
        description: |
          Implemented, and maintained the Data Center network infra for a banking solution provider.
          Tech Stack: Cisco, Juniper, Ansible, Python.
      - layout: left
        title: ITO
        sub_title: Lead System and Network Engineer
        caption: 2011 ‚Äì 2016
        description: |
          Led a team responsible for the design, deployment, and maintenance of 10 major datacenters.
      - layout: left
        title: Rasa Samaneh Paytakht
        sub_title: CEO/CTO
        caption: 2010 ‚Äì 2011
        description: |
          Founded and led a tech company focused on SaaS platform development and deployment.
      - layout: left
        title: Viera (Pooya Andish Vatan)
        sub_title: IT Administrator
        caption: 2008 ‚Äì 2010
        description: |
          System infrastructure management and server administration.
      - layout: left
        title: Tejarat Hooshmand Zomorrod
        sub_title: Java Developer
        caption: 2005 ‚Äì 2008
        description: |
          Developed enterprise-level J2EE applications.
      - layout: left
        title: Farnam
        sub_title: System Administrator
        caption: 2003 ‚Äì 2005
        description: |
          Administered IT infrastructure.

  - title: Certificates
    layout: list
    content:
      - layout: left
        caption: 2025 ‚Äì 2027
        title: Oracle Cloud Infrastructure 2025 Certified Architect Associate
        description: |
          Issued by Oracle Cloud, click <a href="https://catalog-education.oracle.com/ords/certview/sharebadge?id=BEE0049F6F70C9DA038B08AA634D519F18B1F6FAFFF495228CF8BB584B8A0C97">here</a> to view the certificate.
      - layout: left
        caption: 2025 ‚Äì 2027
        title: Oracle Cloud Infrastructure 2025 Certified Developer Professional
        description: |
          Issued by Oracle Cloud, click <a href="https://catalog-education.oracle.com/ords/certview/sharebadge?id=E0F6BEE3A97CCDC7A0493C243B94436743D36FD2D5FBAB0832D02F4B76FF0838">here</a> to view the certificate.
      - layout: left
        caption: 2025 ‚Äì 2027
        title: Oracle Cloud Infrastructure 2025 Certified DevOps Professional
        description: |
          Issued by Oracle Cloud, click <a href="https://catalog-education.oracle.com/ords/certview/sharebadge?id=989F255539B760C8051C923CD9D3F56802AE249093FE0747F74BC277DDA22B4F">here</a> to view the certificate.
      - layout: left
        title: Professional Cloud DevOps Engineer
        caption: 2024 ‚Äì 2026
        description: |
          Issued by Google Cloud, click <a href="https://www.credly.com/badges/5a3e5f9a-8628-42af-8df1-8d5542d04bc5">here</a> to view the certificate.
      - layout: left
        title: Professional Cloud Architect
        caption: 2023 ‚Äì 2025
        description: |
          Issued by Google Cloud, click <a href="https://www.credly.com/badges/a7ad59cb-a92a-4871-a3b5-b05873723096">here</a> to view the certificate.
      - layout: left
        title: Certified Kubernetes Administrator (CKA)
        caption: 2023 ‚Äì 2026
        description: |
          Issued by The Linux Foundation, click <a href="https://www.credly.com/badges/344bca78-ef94-493b-9f91-ac310a9be35c/public_url">here</a> to view the certificate.
      - layout: left
        caption: 2023
        title: GitLab Certified CI/CD Associate
        description: |
          Issued by GitLab, click <a href="https://www.credly.com/badges/5e7d98de-0211-4f1f-a476-d2fa01c36cfd">here</a> to view the certificate.

  - title: Projects
    layout: list
    content:
      - layout: left
        title: Geo-locational Public DNS Servers
        caption: 2016
        description: |
          Tech Stack: Bind, Zebra, Cisco ASR, BGP AnyCast.
      - layout: left
        title: Public Email System
        caption: 2015
        description: |
          Tech Stack: GlusterFS, Postfix, Dovecot, OpenLDAP, MySQL (Galera cluster).
      - layout: left
        title: Designing & Implementing 10 Datacenters
        caption: 2013 ‚Äì 2015
        description: |
          Tech Stack: OpenStack-based private cloud deployments.
      - layout: left
        title: Cash Subsidies Distribution System
        caption: 2014
        description: |
          Tech Stack: Apache Storm, Hadoop, Cassandra, J2EE.
      - layout: left
        title: Enterprise Portal Development
        caption: 2015
        description: |
          Tech Stack: Liferay platform.
      - layout: left
        title: Goods Distribution Webservice
        caption: 2014
        description: |
          Tech Stack: J2EE and Oracle RAC for high availability.
      - layout: left
        title: Yooz Search Engine Project
        caption: 2014 ‚Äì 2015
        description: |
          Tech Stack: Big Data Search Engine with Hadoop, Flume, and Nutch.

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Kashan
        caption: 2003 ‚Äì 2008
        sub_title: BSc Computer Science
      - layout: left
        title: University of Tehran
        caption: 2008 ‚Äì 2011
        sub_title: Master of Applied Mathematics
        description: |
          Specialization: Graph Theory
      - layout: left
        title: Ferdowsi University of Mashhad
        caption: 2011 ‚Äì 2017
        sub_title: PhD of Applied Mathematics
        description: |
          Research Focus: Distance-Based Graph Invariants

  - title: A Little More About Me
    layout: text
    content: |
      Outside the tech world, I have a few passions:
      - üé∏ Playing Guitar (especially Rock and Post-Rock)
      - üé¨ Cinephilia (I breathe movies)
      - üìö Bibliophilia (Books are my second home)
      - üì∏ Photography (film photographer move towards digital)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: ha36d/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
