services:
  jekyll:
    # build once, or replace with "image: jekyll:local" if you push to a registry
    build:
      context: .
      dockerfile: Dockerfile
    image: jekyll
    working_dir: /site
    volumes:
      - .:/site:delegated
      - bundle_cache:/usr/local/bundle
    environment:
      BUNDLE_PATH: /usr/local/bundle
    restart: unless-stopped
    ports:
      - "4000:4000"
    command: >
      bundle exec jekyll serve
      --host 0.0.0.0
      --port 4000

  build:
    build:
      context: .
      dockerfile: Dockerfile
    image: jekyll
    working_dir: /site
    volumes:
      - .:/site:delegated
      - bundle_cache:/usr/local/bundle
    environment:
      BUNDLE_PATH: /usr/local/bundle
    command: >
      bundle exec jekyll build

  bundle:
    build:
      context: .
      dockerfile: Dockerfile
    image: jekyll
    working_dir: /site
    volumes:
      - .:/site:delegated
      - bundle_cache:/usr/local/bundle
    environment:
      BUNDLE_PATH: /usr/local/bundle
    command: >
      bundle install --retry 5 --jobs 20

volumes:
  bundle_cache: